version: "1.0"
lastUpdated: "2024-01-01T00:00:00Z"

groups:
  blog-agents:
    agents:
      - id: writer
        fqdn: localhost:8002
        proxyId: proxy-follower
        healthEndpoint: /health
        agentCardEndpoint: /.well-known/agent.json
        capabilities: ["message/send", "message/stream"]
        a2aCapabilities:
          streaming: true
          pushNotifications: false
          stateTransitionHistory: true
      - id: critic
        fqdn: localhost:8001
        proxyId: proxy-follower
        healthEndpoint: /health
        agentCardEndpoint: /.well-known/agent.json
        capabilities: ["message/send", "message/stream"]
        a2aCapabilities:
          streaming: true
          pushNotifications: true
          stateTransitionHistory: false

  research-agents:
    agents:
      - id: researcher
        fqdn: researcher.local:8003
        proxyId: proxy-1
        healthEndpoint: /health
        agentCardEndpoint: /.well-known/agent.json
        capabilities: ["message/send", "search", "message/stream"]
        a2aCapabilities:
          streaming: true
          pushNotifications: false
          stateTransitionHistory: true
          searchCapabilities: ["web", "documents", "knowledge_base"]
