proxy:
  id: "proxy-1"
  role: "coordinator"
  port: 8080

servicebus:
  namespace: "a2aproxy"
  # connectionString: "Endpoint=sb://a2aproxy.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=YOUR_ACTUAL_KEY_HERE"
  defaultMessageTtl: 3600  # 1 hour
  maxRetryCount: 3
  receiveTimeout: 30  # seconds

# This proxy is a coordinator that doesn't host agents directly
# It only manages Service Bus topics and forwards requests
hostedAgents: {}

# Coordinator subscriptions - receives responses from agent groups it manages
subscriptions:
  - group: "blog-agents"
    filter: "messageType = 'response' AND toProxy = 'proxy-1'"
  - group: "research-agents" 
    filter: "messageType = 'response' AND toProxy = 'proxy-1'"
  - group: "notifications"
    filter: "messageType = 'notification' AND (toProxy = 'proxy-1' OR toProxy IS NULL)"

limits:
  maxConcurrentStreams: 200
  maxMessageSize: 1048576  # 1MB
  streamBufferSize: 10485760  # 10MB
  queueDepthThreshold: 5000

monitoring:
  metricsPort: 9090
  healthPort: 8081
  logLevel: "info"

sessions:
  store_type: "file"
  file_store:
    base_directory: "./data/sessions"
  default_ttl: 3600  # 1 hour
  cleanup_interval: 300  # 5 minutes
  max_sessions: 10000

agentGroups:
  - name: "blog-agents"
    description: "Blog writing and editing agents"
    maxMessageSizeMB: 2
    messageTTLSeconds: 3600
    enablePartitioning: true
    duplicateDetectionWindowMinutes: 10
  - name: "research-agents"
    description: "Research and analysis agents"
    maxMessageSizeMB: 5
    messageTTLSeconds: 7200
    enablePartitioning: true
    duplicateDetectionWindowMinutes: 15

# Agent registry - coordinator needs to know about all agents
# Todo: enable auto-discovery of agents via Service Bus topics
agentRegistry:
  version: "1.0"
  lastUpdated: "2024-12-19T10:00:00Z"
  groups:
    blog-agents:
      agents:
        - id: "writer"
          proxyId: "proxy-follower"
          healthEndpoint: "/health"
          agentCardEndpoint: "/.well-known/agent.json"
          capabilities:
            - "text-generation"
            - "blog-writing"
          a2aCapabilities:
            streaming: true
            stateTransitionHistory: false
        
        - id: "critic"
          proxyId: "proxy-follower"
          healthEndpoint: "/health"
          agentCardEndpoint: "/.well-known/agent.json"
          capabilities:
            - "text-analysis"
            - "blog-review"
          a2aCapabilities:
            streaming: true
            stateTransitionHistory: false

    research-agents:
      agents:
        - id: "researcher"
          proxyId: "proxy-3"
          healthEndpoint: "/health"
          agentCardEndpoint: "/.well-known/agent.json"
          capabilities:
            - "web-search"
            - "data-analysis"
          a2aCapabilities:
            streaming: false
            stateTransitionHistory: true
